export const presetPacks = [
	{
		id: 1,
		name: 'Morphin Master (Everything so far)',
		boxes: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'],
	},
	{ id: 2, name: 'All In-Wave 1', boxes: ['A', 'B', 'C', 'D', 'I'] },
	{ id: 3, name: 'All In-Wave 2', boxes: ['F', 'H', 'J', 'K'] },
];

export const boxes = [
	{ name: 'Heroes of the Grid Base Game', id: 'A' },
	{ name: 'Kickstarter Exclusives Box #1', id: 'B' },
	{ name: 'Shattered Grid', id: 'C' },
	{ name: 'Villian Pack #1', id: 'D' },
	{ name: 'Bulk and Skull Rangers', id: 'E' },
	{ name: 'Zeo Rangers', id: 'F' },
	{ name: 'Allies Pack #1', id: 'G' },
	{ name: 'Legendar Ranger: Tommy Oliver', id: 'H' },
	{ name: 'Cyclopsis', id: 'I' },
	{ name: 'Mega Goldar', id: 'J' },
	{
		name: 'Kickstarter Exclusives #2: Zeo Red Battlezord and Gold Zeo Ranger',
		id: 'K',
	},
	{
		name: 'Rise of the Psycho Rangers',
		id: 'L',
	},
	{
		name: 'Villian Pack #2',
		id: 'M',
	},
];

export const soldiers = [
	{ id: 1001, name: 'Putty Patrollers', box: 'A', image: '' },
	{ id: 1002, name: 'Super Putty Patrollers', box: 'A', image: '' },
	{ id: 1003, name: 'Tenga Warriors', box: 'B', image: '' },
	{ id: 1004, name: 'Z-Putties', box: 'B', image: '' },
	{ id: 1005, name: 'Mastadon Troopers', box: 'C', image: '' },
	{ id: 1006, name: 'Quantrons', box: 'L', image: '' },
];

export const rangers = [
	{ id: 6, name: 'Kimberly Ann Hart', power: 'Mighty Morphin Pink', box: 'A' },
	{ id: 7, name: 'Jason Lee Scott', power: 'Mighty Morphin Red', box: 'A' },
	{ id: 8, name: 'Trini Kwan', power: 'Mighty Morphin Yellow', box: 'A' },
	{ id: 9, name: 'Zack Taylor', power: 'Mighty Morphin Black', box: 'A' },
	{ id: 10, name: 'Billy Cranston', power: 'Mighty Morphin Blue', box: 'A' },
	{
		id: 11,
		name: 'Eugene "Skull" Skullovitch',
		power: 'Mighty Morphin Orange',
		box: 'E',
	},
	{
		id: 12,
		name: 'Farkas "Bulk" Bulkmeier',
		power: 'Mighty Morphin Purple',
		box: 'E',
	},
	{ id: 13, name: 'Lauren Shiba', power: 'Super Samurai Red', box: 'C' },
	{ id: 14, name: 'Marvin Shih', power: 'HyperForce Red', box: 'C' },
	{ id: 15, name: 'Eddie Banks', power: 'HyperForce Blue', box: 'C' },
	{ id: 16, name: 'Chloe Ashford', power: 'HyperForce Pink', box: 'C' },
	{ id: 17, name: 'Jack Thomas', power: 'HyperForce Yellow', box: 'C' },
	{ id: 18, name: 'Vesper Vasquez', power: 'HyperForce Black', box: 'C' },
	{ id: 19, name: 'Jen Scotts', power: 'Time Force Pink', box: 'C' },
	{ id: 20, name: 'Kat Hillard', power: 'Mighty Morphin Pink', box: 'B' },
	{ id: 21, name: 'Aisha Campbell', power: 'Mighty Morphin Yellow', box: 'B' },
	{ id: 22, name: 'Rocky DeSantos', power: 'Mighty Morphin Red', box: 'B' },
	{ id: 23, name: 'Adam Park', power: 'Mighty Morphin Black', box: 'B' },
	{
		id: 24,
		name: 'Jason Lee Scott',
		power: 'Mighty Morphin Red',
		subset: 'Dragon Shield',
		box: 'B',
	},
	{ id: 25, name: 'Kimberly Ann Hart', power: 'Rebel Ranger Slayer', box: 'B' },
	{
		id: 26,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Loner',
		box: 'B',
	},
	{
		id: 27,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Guardian Light',
		box: 'B',
	},
	{
		id: 32,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Loner',
		box: 'H',
	},
	{
		id: 33,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Guardian Light',
		box: 'H',
	},
	{
		id: 28,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Rallying Light',
		box: 'H',
	},
	{
		id: 29,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Gift of the Dragon',
		box: 'H',
	},
	{ id: 30, name: 'Tommy Oliver', power: 'Dino Thunder Black', box: 'H' },
	{ id: 1, name: 'Tommy Oliver', power: 'Turbo Red', box: 'H' },
	{ id: 2, name: 'Tommy Oliver', power: 'Zeo Ranger V Red', box: 'F' },
	{ id: 3, name: 'Adam Park', power: 'Zeo Ranger IV Green', box: 'F' },
	{ id: 4, name: 'Rocky DeSantos', power: 'Zeo Ranger III Blue', box: 'F' },
	{ id: 5, name: 'Tanya Sloan', power: 'Zeo Ranger II Yellow', box: 'F' },
	{ id: 34, name: 'Kat Hillard', power: 'Zeo Ranger I Pink', box: 'F' },
	{ id: 35, name: 'Jason Lee Scott', power: 'Zeo Gold Ranger', box: 'K' },
	{ id: 36, name: 'Trey of Triforia', power: 'Zeo Gold Ranger', box: 'K' },
	{ id: 37, name: 'Jason Lee Scott', power: 'Zeo Gold Ranger', box: 'G' },
	{ id: 38, name: 'Trey of Triforia', power: 'Zeo Gold Ranger', box: 'G' },
	{ id: 39, name: '', power: 'Ninjor', box: 'G' },
	{ id: 40, name: '', power: 'Phantom Ranger', box: 'G' },
	{ id: 41, name: 'Mike Corbett', power: 'Magna Defender', box: 'G' },
	{ id: 42, name: 'Anubis Cruger', power: 'S.P.D. Shadow Ranger', box: 'G' },
	{ id: 43, name: 'Andros', power: 'Red Space Ranger', box: 'L' },
	{ id: 44, name: 'Carlos Vallerte', power: 'Black Space Ranger', box: 'L' },
	{ id: 45, name: 'T.J. Johnson', power: 'Blue Space Ranger', box: 'L' },
	{ id: 46, name: 'Ashley Hammond', power: 'Yellow Space Ranger', box: 'L' },
	{ id: 47, name: 'Cassie Chan', power: 'Pink Space Ranger', box: 'L' },
];

export const megazords = [
	{ id: 9001, name: 'Dino Megazord', box: 'A' },
	{ id: 9002, name: 'Chronos HyperForce Megazord', box: 'C' },
	{ id: 9003, name: 'Zeo Megazord', box: 'F' },
	{ id: 9004, name: 'Dragonzord Battle Mode', box: 'H' },
	{ id: 9005, name: 'Delta Command Megazord', box: 'G' },
	{ id: 9006, name: 'Mega Voyager', box: 'L' },
];

export const zords = [
	{ id: 8001, name: 'Pterodactyl', box: 'A' },
	{ id: 8002, name: 'Triceratops', box: 'A' },
	{ id: 8003, name: 'Mastodon', box: 'A' },
	{ id: 8004, name: 'Saber-Toothed Tiger', box: 'A' },
	{ id: 8005, name: 'Tyrannosaurus', box: 'A' },
	{ id: 8006, name: 'Dragonzord', box: 'B' },
	{ id: 8007, name: 'White Tigerzord', box: 'B' },
	{ id: 8008, name: 'Ram Hyper Zord', box: 'C' },
	{ id: 8009, name: 'Phoenix Hyper Zord', box: 'C' },
	{ id: 8010, name: 'Serpent Hyper Zord', box: 'C' },
	{ id: 8011, name: 'Cerberus Hyper Zord', box: 'C' },
	{ id: 8012, name: 'Lion Hyper Zord', box: 'C' },
	{ id: 8013, name: 'Gravezord', box: 'C' },
	{ id: 8014, name: 'Bullzord', box: 'C' },
	{ id: 8015, name: 'Time Flyer 5', box: 'C' },
	{ id: 8016, name: 'Featherdactyl', box: 'E' },
	{ id: 8017, name: 'Baconodon', box: 'E' },
	{ id: 8018, name: 'Brachiozord', box: 'H' },
	{ id: 8019, name: 'Lightning Cruiser', box: 'H' },
	{ id: 8020, name: 'White Tigerzord', box: 'H' },
	{ id: 8021, name: 'Dragonzord', box: 'H' },
	{ id: 8022, name: 'Zeo Zord V', box: 'F' },
	{ id: 8023, name: 'Zeo Zord IV', box: 'F' },
	{ id: 8024, name: 'Zeo Zord III', box: 'F' },
	{ id: 8025, name: 'Zeo Zord II', box: 'F' },
	{ id: 8026, name: 'Zeo Zord I', box: 'F' },
	{ id: 8027, name: 'Zeo Red Battlezord', box: 'K' },
	{ id: 8028, name: 'Pyramidas', box: 'K' },
	{ id: 8029, name: 'Ninjor Battle Mode', box: 'G' },
	{ id: 8030, name: 'Pyramidas', box: 'G' },
	{ id: 8031, name: 'Artillatron', box: 'G' },
	{ id: 8032, name: 'Torozord', box: 'G' },
	{ id: 8033, name: 'Delta Base', box: 'G' },
	{ id: 8034, name: 'Mega V1', box: 'L' },
	{ id: 8035, name: 'Mega V2', box: 'L' },
	{ id: 8036, name: 'Mega V3', box: 'L' },
	{ id: 8037, name: 'Mega V4', box: 'L' },
	{ id: 8038, name: 'Mega V5', box: 'L' },
];

export const masters = [
	{ id: 3001, name: 'Rita Repulsa', box: 'A' },
	{ id: 3002, name: 'Master Vile', box: 'D' },
	{ id: 3003, name: 'Rito Revolto', box: 'D' },
	{ id: 3004, name: 'Lord Drakkon', box: 'C' },
	{ id: 3005, name: 'Cyclopsis', box: 'I' },
	{ id: 3006, name: 'Mega Goldar', box: 'J' },
	{ id: 3007, name: 'Scorpina', box: 'B' },
	{ id: 3008, name: 'Goldar', box: 'B' },
	{ id: 3009, name: 'Lord Zedd', box: 'B' },
	{ id: 3010, name: 'Wizard of Deception', box: 'B' },
	{ id: 3011, name: 'Psycho Rangers', box: 'L' },
	{ id: 3012, name: 'King Mondo', box: 'M' },
	{ id: 3013, name: 'Louie Kaboom', box: 'M' },
];

export const monsters = [
	{ id: 2001, name: 'Madame Woe', box: 'A' },
	{ id: 2002, name: 'Pudgy Pig', box: 'A' },
	{ id: 2003, name: 'Bones', box: 'A' },
	{ id: 2004, name: 'Knasty Knight', box: 'A' },
	{ id: 2005, name: 'Commander Crayfish', box: 'D' },
	{ id: 2006, name: 'Polluticorn', box: 'D' },
	{ id: 2007, name: 'Ranger Slayer', box: 'C' },
	{ id: 2008, name: 'Black Dragon', box: 'C' },
	{ id: 2009, name: 'Pumpkin Rapper', box: 'B' },
	{ id: 2010, name: 'Eye Guy', box: 'B' },
	{ id: 2011, name: 'Rhinoblaster', box: 'B' },
	{ id: 2012, name: 'Robogoat', box: 'B' },
	{ id: 2013, name: 'Evil Green Ranger', box: 'B' },
	{ id: 2014, name: 'Finster', box: 'B' },
	{ id: 2015, name: 'Primator', box: 'B' },
	{ id: 2016, name: 'Evil Robot Tommy', box: 'H' },
	{ id: 2017, name: 'Psycho Red', box: 'L' },
	{ id: 2018, name: 'Psycho Black', box: 'L' },
	{ id: 2019, name: 'Psycho Blue', box: 'L' },
	{ id: 2020, name: 'Psycho Pink', box: 'L' },
	{ id: 2021, name: 'Psycho Yellow', box: 'L' },
	{ id: 2022, name: 'Psycho Green', box: 'L' },
	{ id: 2023, name: 'Prince Gasket & Princess Archerina', box: 'M' },
	{ id: 2024, name: 'Prince Gasket', box: 'M' },
	{ id: 2025, name: 'Princess Archerina', box: 'M' },
	{ id: 2026, name: 'General Venjix', box: 'M' },
];
