export const boxes = [
	{ name: 'Heroes of the Grid Base Game', id: 'A', type: 'big box' },
	{ name: 'Kickstarter Exclusives Box #1', id: 'B', type: 'big box' },
	{ name: 'Shattered Grid', id: 'C', type: 'big box' },
	{ name: 'Villian Pack #1', id: 'D', type: 'villains' },
	{ name: 'Bulk and Skull Rangers', id: 'E', type: 'rangers' },
	{ name: 'Zeo Rangers', id: 'F', type: 'rangers' },
	{ name: 'Allies Pack #1', id: 'G', type: 'rangers' },
	{ name: 'Legendar Ranger: Tommy Oliver', id: 'H', type: 'rangers' },
	{ name: 'Cyclopsis', id: 'I', type: 'villains' },
	{ name: 'Mega Goldar', id: 'J', type: 'villains' },
	{
		name: 'Kickstarter Exclusives #2: Zeo Red Battlezord and Gold Zeo Ranger',
		id: 'K',
		type: 'extras',
	},
	{ name: 'Rise of the Psycho Rangers', id: 'L', type: 'big box' },
	{ name: 'Villain Pack #2: Machine Empire', id: 'M', type: 'villains' },
	{ name: 'Legendary Rangers: Forever Rangers', id: 'N', type: 'rangers' },
	{
		name: 'Fan Appreciation Pack: Titanus and Ultrazord',
		id: 'O',
		type: 'extras',
	},
	{ name: 'Squatt and Baboo Character Pack', id: 'P', type: 'villains' },
	{ name: 'Villain Pack #3: Legacy of Evil', id: 'Q', type: 'villains' },
	{ name: 'Rangers United', id: 'R', type: 'big box' },
	{ name: 'Light and Darkness', id: 'S', type: 'big box' },
	{ name: 'Dino Thunder', id: 'T', type: 'rangers' },
	{ name: 'Time Force', id: 'U', type: 'rangers' },
	{ name: 'S.P.D.', id: 'V', type: 'rangers' },
	{ name: 'Allies Pack #2', id: 'W', type: 'rangers' },
	{ name: 'Allies Pack #3', id: 'X', type: 'rangers' },
	{ name: 'Villian Pack #4: A Dark Turn', id: 'Y', type: 'villains' },
	{ name: 'Villian Pack #5: Trouble Through Time', id: 'Z', type: 'villains' },
	{ name: 'Shadow of Venjix', id: 'AA', type: 'big box' },
	{ name: 'Santa Vs. Heximas', id: 'AB', type: 'extras' },
	{ name: 'Merciless Minions Pack #1', id: 'AC', type: 'foot soldiers' },
	{ name: 'Merciless Minions Pack #2', id: 'AD', type: 'foot soldiers' },
	{ name: 'Zord Pack #1', id: 'AE', type: 'extras' },
	{ name: 'Zord Pack #2', id: 'AF', type: 'extras' },
	{ name: 'Zord Pack #3', id: 'AG', type: 'extras' },
	{ name: 'Arsenal Pack', id: 'AH', type: 'rangers' },
	{ name: 'RPM', id: 'AI', type: 'rangers' },
	{ name: 'Allies Pack #4', id: 'AJ', type: 'rangers' },
	{ name: 'Foot Soldier Promo Pack #1', id: 'AK', type: 'foot soldiers' },
];

export const soldiers = [
	{ id: 1001, name: 'Putty Patrollers', box: 'A', image: '' },
	{ id: 1002, name: 'Super Putty Patrollers', box: 'A', image: '' },
	{ id: 1003, name: 'Tenga Warriors', box: 'B', image: '' },
	{ id: 1004, name: 'Z-Putties', box: 'B', image: '' },
	{ id: 1005, name: 'Mastadon Troopers', box: 'C', image: '' },
	{ id: 1006, name: 'Quantrons', box: 'L', image: '' },
	{ id: 1007, name: 'Tronics', box: 'R', image: '' },
	{ id: 1008, name: 'Rinshi', box: 'S', image: '' },
	{ id: 1009, name: 'Cogs', box: 'AC', image: '' },
	{ id: 1010, name: 'Cyclobots', box: 'AC', image: '' },
	{ id: 1011, name: 'Tyrannodrones', box: 'AD', image: '' },
	{ id: 1012, name: 'Krybots', box: 'AD', image: '' },
	{ id: 1013, name: 'Ranger Sentries', box: 'AK', image: '' },
];

export const rangers = [
	{ id: 6, name: 'Kimberly Ann Hart', power: 'Mighty Morphin Pink', box: 'A' },
	{ id: 7, name: 'Jason Lee Scott', power: 'Mighty Morphin Red', box: 'A' },
	{ id: 8, name: 'Trini Kwan', power: 'Mighty Morphin Yellow', box: 'A' },
	{ id: 9, name: 'Zack Taylor', power: 'Mighty Morphin Black', box: 'A' },
	{ id: 10, name: 'Billy Cranston', power: 'Mighty Morphin Blue', box: 'A' },
	{
		id: 11,
		name: 'Eugene "Skull" Skullovitch',
		power: 'Mighty Morphin Orange',
		box: 'E',
	},
	{
		id: 12,
		name: 'Farkas "Bulk" Bulkmeier',
		power: 'Mighty Morphin Purple',
		box: 'E',
	},
	{ id: 13, name: 'Lauren Shiba', power: 'Super Samurai Red', box: 'C' },
	{ id: 14, name: 'Marvin Shih', power: 'HyperForce Red', box: 'C' },
	{ id: 15, name: 'Eddie Banks', power: 'HyperForce Blue', box: 'C' },
	{ id: 16, name: 'Chloe Ashford', power: 'HyperForce Pink', box: 'C' },
	{ id: 17, name: 'Jack Thomas', power: 'HyperForce Yellow', box: 'C' },
	{ id: 18, name: 'Vesper Vasquez', power: 'HyperForce Black', box: 'C' },
	{ id: 19, name: 'Jen Scotts', power: 'Time Force Pink', box: 'C' },
	{ id: 20, name: 'Kat Hillard', power: 'Mighty Morphin Pink', box: 'B' },
	{ id: 21, name: 'Aisha Campbell', power: 'Mighty Morphin Yellow', box: 'B' },
	{ id: 22, name: 'Rocky DeSantos', power: 'Mighty Morphin Red', box: 'B' },
	{ id: 23, name: 'Adam Park', power: 'Mighty Morphin Black', box: 'B' },
	{
		id: 24,
		name: 'Jason Lee Scott',
		power: 'Mighty Morphin Red',
		subset: 'Dragon Shield',
		box: 'B',
	},
	{ id: 25, name: 'Kimberly Ann Hart', power: 'Rebel Ranger Slayer', box: 'B' },
	{
		id: 26,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Loner',
		box: 'B',
	},
	{
		id: 27,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Guardian Light',
		box: 'B',
	},
	{
		id: 32,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Loner',
		box: 'H',
	},
	{
		id: 33,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Guardian Light',
		box: 'H',
	},
	{
		id: 28,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Rallying Light',
		box: 'H',
	},
	{
		id: 29,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Gift of the Dragon',
		box: 'H',
	},
	{ id: 30, name: 'Tommy Oliver', power: 'Dino Thunder Black', box: 'H' },
	{ id: 1, name: 'Tommy Oliver', power: 'Turbo Red', box: 'H' },
	{ id: 2, name: 'Tommy Oliver', power: 'Zeo V Red', box: 'F' },
	{ id: 3, name: 'Adam Park', power: 'Zeo IV Green', box: 'F' },
	{ id: 4, name: 'Rocky DeSantos', power: 'Zeo III Blue', box: 'F' },
	{ id: 5, name: 'Tanya Sloan', power: 'Zeo II Yellow', box: 'F' },
	{ id: 34, name: 'Kat Hillard', power: 'Zeo I Pink', box: 'F' },
	{ id: 35, name: 'Jason Lee Scott', power: 'Zeo Gold', box: 'K' },
	{ id: 36, name: 'Trey of Triforia', power: 'Zeo Gold', box: 'K' },
	{ id: 37, name: 'Jason Lee Scott', power: 'Zeo Gold', box: 'G' },
	{ id: 38, name: 'Trey of Triforia', power: 'Zeo Gold', box: 'G' },
	{ id: 39, name: '', power: 'Ninjor', box: 'G' },
	{ id: 40, name: '', power: 'Phantom Ranger', box: 'G' },
	{ id: 41, name: 'Mike Corbett', power: 'Magna Defender', box: 'G' },
	{ id: 42, name: 'Anubis Cruger', power: 'S.P.D. Shadow', box: 'G' },
	{ id: 43, name: 'Andros', power: 'Red Space', box: 'L' },
	{ id: 44, name: 'Carlos Vallerte', power: 'Black Space', box: 'L' },
	{ id: 45, name: 'T.J. Johnson', power: 'Blue Space', box: 'L' },
	{ id: 46, name: 'Ashley Hammond', power: 'Yellow Space', box: 'L' },
	{ id: 47, name: 'Cassie Chan', power: 'Pink Space', box: 'L' },
	{ id: 48, name: 'Rocky DeSantos', power: 'Mighty Morphin Red', box: 'N' },
	{ id: 49, name: 'Adam Park', power: 'Mighty Morphin Black', box: 'N' },
	{ id: 50, name: 'Kat Hillard', power: 'Mighty Morphin Pink', box: 'N' },
	{ id: 51, name: 'Aisha Campbell', power: 'Mighty Morphin Yellow', box: 'N' },
	{ id: 52, name: 'Alpha 5', power: 'Servant of Zordon', box: 'N' },
	{ id: 53, name: 'Devon Daniels', power: 'Beast Morphers Red', box: 'R' },
	{ id: 54, name: 'Ravi Shaw', power: 'Beast Morphers Blue', box: 'R' },
	{ id: 55, name: 'Zoey Reeves', power: 'Beast Morphers Yellow', box: 'R' },
	{ id: 56, name: 'Jason Lee Scott', power: 'Omega Red', box: 'R' },
	{ id: 57, name: 'Zack Taylor', power: 'Omega Black', box: 'R' },
	{ id: 58, name: 'Trini Kwan', power: 'Omega Yellow', box: 'R' },
	{ id: 59, name: 'Ellarien', power: 'Violet Solar', box: 'R' },
	{ id: 60, name: 'Merrick Baliton', power: 'Wild Force Lunar Wolf', box: 'S' },
	{ id: 61, name: 'Leanbow', power: 'Wolf Warrior', box: 'S' },
	{ id: 62, name: 'Tyzonn', power: 'Operation Overdrive Mercury', box: 'S' },
	{ id: 63, name: 'Jarrod', power: 'Black Lion Warrior', box: 'S' },
	{ id: 64, name: 'Heckyl', power: 'Dino Charge Dark', box: 'S' },
	{ id: 65, name: 'Conner McKnight', power: 'Dino Thunder Red', box: 'T' },
	{ id: 66, name: 'Ethan James', power: 'Dino Thunder Blue', box: 'T' },
	{ id: 67, name: 'Kira Ford', power: 'Dino Thunder Yellow', box: 'T' },
	{ id: 68, name: 'Trent Mercer', power: 'Dino Thunder White', box: 'T' },
	{ id: 69, name: 'Eric Meyers', power: 'Time Force Quantum', box: 'U' },
	{ id: 70, name: 'Wes Collins', power: 'Time Force Red', box: 'U' },
	{ id: 71, name: 'Lucas Kendall', power: 'Time Force Blue', box: 'U' },
	{ id: 72, name: 'Katie Walker', power: 'Time Force Yellow', box: 'U' },
	{ id: 73, name: 'Trip', power: 'Time Force Green', box: 'U' },
	{ id: 74, name: 'Jack Landors', power: 'S.P.D. Red', box: 'V' },
	{ id: 75, name: 'Sky Tate', power: 'S.P.D. Blue', box: 'V' },
	{ id: 76, name: 'Bridge Carson', power: 'S.P.D. Green', box: 'V' },
	{ id: 77, name: 'Z Delgado', power: 'S.P.D. Yellow', box: 'V' },
	{ id: 78, name: 'Sydney Drew', power: 'S.P.D. Pink', box: 'V' },
	{ id: 79, name: 'Cameron Watanabe', power: 'Green Samurai', box: 'W' },
	{ id: 80, name: 'Zhane', power: 'Silver Space', box: 'W' },
	{ id: 81, name: 'Ryan Mitchell', power: 'Titanium', box: 'W' },
	{ id: 82, name: 'Robert "RJ" James', power: 'Jungle Fury Wolf', box: 'W' },
	{ id: 83, name: 'Ryan Mitchell', power: 'Titanium', box: 'W' },
	{ id: 84, name: 'Joe Shih', power: 'Hyperforce Green', box: 'W' },
	{ id: 85, name: 'Udonna', power: 'White Mystic', box: 'X' },
	{ id: 86, name: 'Delphine', power: 'White Aquitar', box: 'X' },
	{ id: 87, name: 'Kendall Morgan', power: 'Dino Charge Purple', box: 'X' },
	{ id: 88, name: 'Karone', power: 'Galaxy Pink', box: 'X' },
	{ id: 89, name: '', power: 'Doctor K', box: 'X' },
	{ id: 90, name: 'Nate Silva', power: 'Beast Morphers Gold', box: 'AA' },
	{ id: 91, name: 'Steel Silva', power: 'Beast Morphers Silver', box: 'AA' },
	{ id: 92, name: '', power: 'Santa Claus', box: 'AB' },
	{ id: 93, name: 'Scott Truman', power: 'RPM Red', box: 'AI' },
	{ id: 94, name: 'Flynn McAllistair', power: 'RPM Blue', box: 'AI' },
	{ id: 95, name: 'Summer Landsdown', power: 'RPM Yellow', box: 'AI' },
	{ id: 96, name: 'Ziggy Grover', power: 'RPM Green', box: 'AI' },
	{ id: 97, name: 'Dillon', power: 'RPM Black', box: 'AI' },
	{ id: 98, name: '', power: 'Blue Senturion', box: 'AJ' },
	{ id: 99, name: 'Hunter Bradley', power: 'Crimson Thunder', box: 'AJ' },
	{ id: 100, name: 'Blake Bradley', power: 'Navy Thunder', box: 'AJ' },
	{ id: 101, name: 'Orion', power: 'Super Megaforce Silver', box: 'AJ' },
	{ id: 102, name: 'Levi Weston', power: 'Ninja Steel Gold', box: 'AJ' },
	{ id: 103, name: 'Nameless Warrior', power: 'Magna Defender', box: 'AJ' },
	{ id: 104, name: 'Morphinaut', power: 'Phantom Ranger', box: 'AJ' },
	{ id: 105, name: 'Matthew Cook', power: 'Mighty Morphin Green', box: 'AJ' },
	{ id: 106, name: 'Tyler NaVarro', power: 'Dino Charge Red', box: 'AH' },
	{ id: 107, name: 'Trini Kwan', power: 'Dragon Armor', box: 'AH' },
	{ id: 108, name: 'Izzy Garcia', power: 'Dino Fury Green', box: 'AH' },
];

export const megazords = [
	{ id: 9001, name: 'Dino Megazord', box: 'A' },
	{ id: 9002, name: 'Chronos HyperForce Megazord', box: 'C' },
	{ id: 9003, name: 'Zeo Megazord', box: 'F' },
	{ id: 9004, name: 'Dragonzord Battle Mode', box: 'H' },
	{ id: 9005, name: 'Delta Command Megazord', box: 'G' },
	{ id: 9006, name: 'Mega Voyager', box: 'L' },
	{ id: 9007, name: 'Mega Tigerzord', box: 'N' },
	{ id: 9008, name: 'Thunder Megazord', box: 'N' },
	{ id: 9009, name: 'Ultrazord', box: 'O' },
	{ id: 9010, name: 'Beast-X Megazord', box: 'R' },
	{ id: 9011, name: 'Solar Megazord', box: 'R' },
	{ id: 9012, name: 'Flash Point Megazord', box: 'S' },
	{ id: 9013, name: 'Predazord', box: 'S' },
	{ id: 9014, name: 'Thundersaurus Megazord', box: 'T' },
	{ id: 9015, name: 'Time Force Megazord', box: 'U' },
	{ id: 9016, name: 'Delta Squad Megazord', box: 'V' },
	{ id: 9017, name: 'Delta Max Megazord', box: 'V' },
	{ id: 9018, name: 'Lightspeed Solarzord', box: 'W' },
	{ id: 9019, name: 'Plesio Charge Megazord', box: 'X' },
	{ id: 9020, name: 'Orion Galaxy Megazord', box: 'X' },
	{ id: 9021, name: 'Beast-X King Ultrazord', box: 'AA' },
	{ id: 9022, name: 'Ninja Megazord', box: 'AE' },
	{ id: 9023, name: 'Ninja FalconMegazord', box: 'AE' },
	{ id: 9024, name: 'Shogun Megazord', box: 'AF' },
	{ id: 9025, name: 'Shogun Ultrazord', box: 'AF' },
	{ id: 9026, name: 'Zeo Mega Battlezord', box: 'AG' },
	{ id: 9027, name: 'Super Zeo Megazord', box: 'AG' },
	{ id: 9028, name: 'High Octane Megazord', box: 'AI' },
	{ id: 9029, name: 'Valvemax Megazord', box: 'AI' },
	{ id: 9030, name: 'Ninja Storm Thunder Megazord', box: 'AJ' },
	{ id: 9031, name: 'Bull Rider Megazord', box: 'AJ' },
];

export const zords = [
	{ id: 8001, name: 'Pterodactyl', box: 'A' },
	{ id: 8002, name: 'Triceratops', box: 'A' },
	{ id: 8003, name: 'Mastodon', box: 'A' },
	{ id: 8004, name: 'Saber-Toothed Tiger', box: 'A' },
	{ id: 8005, name: 'Tyrannosaurus', box: 'A' },
	{ id: 8006, name: 'Dragonzord', box: 'B' },
	{ id: 8007, name: 'White Tigerzord', box: 'B' },
	{ id: 8008, name: 'Ram Hyper Zord', box: 'C' },
	{ id: 8009, name: 'Phoenix Hyper Zord', box: 'C' },
	{ id: 8010, name: 'Serpent Hyper Zord', box: 'C' },
	{ id: 8011, name: 'Cerberus Hyper Zord', box: 'C' },
	{ id: 8012, name: 'Lion Hyper Zord', box: 'C' },
	{ id: 8013, name: 'Gravezord', box: 'C' },
	{ id: 8014, name: 'Bullzord', box: 'C' },
	{ id: 8015, name: 'Time Flyer 5', box: 'C' },
	{ id: 8016, name: 'Featherdactyl', box: 'E' },
	{ id: 8017, name: 'Baconodon', box: 'E' },
	{ id: 8018, name: 'Brachiozord', box: 'H' },
	{ id: 8019, name: 'Lightning Cruiser', box: 'H' },
	{ id: 8020, name: 'White Tigerzord', box: 'H' },
	{ id: 8021, name: 'Dragonzord', box: 'H' },
	{ id: 8022, name: 'Zeo Zord V', box: 'F' },
	{ id: 8023, name: 'Zeo Zord IV', box: 'F' },
	{ id: 8024, name: 'Zeo Zord III', box: 'F' },
	{ id: 8025, name: 'Zeo Zord II', box: 'F' },
	{ id: 8026, name: 'Zeo Zord I', box: 'F' },
	{ id: 8027, name: 'Zeo Red Battlezord', box: 'K' },
	{ id: 8028, name: 'Pyramidas', box: 'K' },
	{ id: 8029, name: 'Ninjor Battle Mode', box: 'G' },
	{ id: 8030, name: 'Pyramidas', box: 'G' },
	{ id: 8031, name: 'Artillatron', box: 'G' },
	{ id: 8032, name: 'Torozord', box: 'G' },
	{ id: 8033, name: 'Delta Base', box: 'G' },
	{ id: 8034, name: 'Mega V1', box: 'L' },
	{ id: 8035, name: 'Mega V2', box: 'L' },
	{ id: 8036, name: 'Mega V3', box: 'L' },
	{ id: 8037, name: 'Mega V4', box: 'L' },
	{ id: 8038, name: 'Mega V5', box: 'L' },
	{ id: 8039, name: 'Red Dragon Thunderzord', box: 'N' },
	{ id: 8040, name: 'Lion Thunderzord', box: 'N' },
	{ id: 8041, name: 'Firebird Thunderzord', box: 'N' },
	{ id: 8042, name: 'Unicorn Thunderzord', box: 'N' },
	{ id: 8043, name: 'Griffin Thunderzord', box: 'N' },
	{ id: 8044, name: 'Power Blaster', box: 'N' },
	{ id: 8045, name: 'Titanus', box: 'O' },
	{ id: 8046, name: 'Racer Zord', box: 'R' },
	{ id: 8047, name: 'Wheeler Zord', box: 'R' },
	{ id: 8048, name: 'Chopper Zord', box: 'R' },
	{ id: 8049, name: 'Omega Red Zord', box: 'R' },
	{ id: 8050, name: 'Omega Black Zord', box: 'R' },
	{ id: 8051, name: 'Omega Yellow Zord', box: 'R' },
	{ id: 8052, name: 'Solar Zord', box: 'R' },
	{ id: 8053, name: 'Alligator Wildzord', box: 'S' },
	{ id: 8054, name: 'Hammerhead Shark Wildzord', box: 'S' },
	{ id: 8055, name: 'Wolf Wildzord', box: 'S' },
	{ id: 8056, name: 'Runner Zords', box: 'S' },
	{ id: 8057, name: 'Lion Animal Spirit', box: 'S' },
	{ id: 8058, name: 'Spino zord', box: 'S' },
	{ id: 8059, name: 'Catastros', box: 'S' },
	{ id: 8060, name: 'Tyrannozord', box: 'T' },
	{ id: 8061, name: 'Tricerazord', box: 'T' },
	{ id: 8062, name: 'Pterazord', box: 'T' },
	{ id: 8063, name: 'Dragozord', box: 'T' },
	{ id: 8064, name: 'Quantasaurus Rex', box: 'U' },
	{ id: 8065, name: 'Time Flyer 1', box: 'U' },
	{ id: 8066, name: 'Time Flyer 2', box: 'U' },
	{ id: 8067, name: 'Time Flyer 3', box: 'U' },
	{ id: 8068, name: 'Time Flyer 4', box: 'U' },
	{ id: 8069, name: 'Shadow Winger', box: 'U' },
	{ id: 8070, name: 'Delta Runner 1', box: 'V' },
	{ id: 8071, name: 'Delta Runner 2', box: 'V' },
	{ id: 8072, name: 'Delta Runner 3', box: 'V' },
	{ id: 8073, name: 'Delta Runner 4', box: 'V' },
	{ id: 8074, name: 'Delta Runner 5', box: 'V' },
	{ id: 8075, name: 'Samurai Star Chopper', box: 'W' },
	{ id: 8076, name: 'Mega Winger', box: 'W' },
	{ id: 8077, name: 'Max Solarzord', box: 'W' },
	{ id: 8078, name: 'Wolf Animal Spirit', box: 'W' },
	{ id: 8079, name: 'Hydra Hyper Zord', box: 'W' },
	{ id: 8080, name: 'White Titan Form', box: 'X' },
	{ id: 8081, name: 'White Battle Borg', box: 'X' },
	{ id: 8082, name: 'Plesio Zord', box: 'X' },
	{ id: 8083, name: 'Wildcat Galactabeast', box: 'X' },
	{ id: 8084, name: 'Project GO-ONGER', box: 'X' },
	{ id: 8085, name: 'Wrecker Zord', box: 'AA' },
	{ id: 8086, name: 'Jet Zord', box: 'AA' },
	{ id: 8087, name: 'Beast-X King Zord', box: 'AA' },
	{ id: 8088, name: 'Reindeer Zord', box: 'AB' },
	{ id: 8089, name: 'Ape Ninjazord', box: 'AE' },
	{ id: 8090, name: 'Bear Ninjazord', box: 'AE' },
	{ id: 8091, name: 'Wolf Ninjazord', box: 'AE' },
	{ id: 8092, name: 'Frog Ninjazord', box: 'AE' },
	{ id: 8093, name: 'Crane Ninjazord', box: 'AE' },
	{ id: 8094, name: 'Falcon Ninjazord', box: 'AE' },
	{ id: 8095, name: 'Red Shogunzord', box: 'AF' },
	{ id: 8096, name: 'Yellow Shogunzord', box: 'AF' },
	{ id: 8097, name: 'Blue Shogunzord', box: 'AF' },
	{ id: 8098, name: 'Black Shogunzord', box: 'AF' },
	{ id: 8099, name: 'White Shogunzord', box: 'AF' },
	{ id: 8100, name: 'Super Zeo Zord 1', box: 'AG' },
	{ id: 8101, name: 'Super Zeo Zord 2', box: 'AG' },
	{ id: 8102, name: 'Super Zeo Zord 3', box: 'AG' },
	{ id: 8103, name: 'Super Zeo Zord 4', box: 'AG' },
	{ id: 8104, name: 'Super Zeo Zord 5', box: 'AG' },
	{ id: 8105, name: 'Warrior Wheel', box: 'AG' },
	{ id: 8106, name: 'Eagle Racer', box: 'AI' },
	{ id: 8107, name: 'Lion Hauler', box: 'AI' },
	{ id: 8108, name: 'Bear Crawler', box: 'AI' },
	{ id: 8109, name: 'Tail Spinner', box: 'AI' },
	{ id: 8110, name: 'Wolf Cruiser', box: 'AI' },
	{ id: 8111, name: 'Robo Racer', box: 'AJ' },
	{ id: 8112, name: 'Crimson Insectizord', box: 'AJ' },
	{ id: 8113, name: 'Navy Beetlezord', box: 'AJ' },
	{ id: 8114, name: 'Q-Rex Drill', box: 'AJ' },
	{ id: 8115, name: 'Ninja Bull Zord & Robo Rider Zord', box: 'AJ' },
	{ id: 8116, name: 'T-Rex Zord', box: 'AH' },
	{ id: 8117, name: 'Tiger Claw Zord', box: 'AH' },
	{ id: 8118, name: 'Mega Black Dragon', box: 'AH' },
];

export const masters = [
	{ id: 3001, name: 'Rita Repulsa', box: 'A' },
	{ id: 3002, name: 'Master Vile', box: 'D' },
	{ id: 3003, name: 'Rito Revolto', box: 'D' },
	{ id: 3004, name: 'Lord Drakkon', box: 'C' },
	{ id: 3005, name: 'Cyclopsis', box: 'I' },
	{ id: 3006, name: 'Mega Goldar', box: 'J' },
	{ id: 3007, name: 'Scorpina', box: 'B' },
	{ id: 3008, name: 'Goldar', box: 'B' },
	{ id: 3009, name: 'Lord Zedd', box: 'B' },
	{ id: 3010, name: 'Wizard of Deception', box: 'B' },
	{ id: 3011, name: 'Psycho Rangers', box: 'L' },
	{ id: 3012, name: 'King Mondo', box: 'M' },
	{ id: 3013, name: 'Louie Kaboom', box: 'M' },
	{ id: 3014, name: 'Divatox', box: 'Q' },
	{ id: 3015, name: 'Thrax', box: 'Q' },
	{ id: 3016, name: 'Kiya', box: 'R' },
	{ id: 3017, name: 'Dai Shi', box: 'S' },
	{ id: 3018, name: 'Mesogog', box: 'Y' },
	{ id: 3019, name: 'Astronema', box: 'Y' },
	{ id: 3020, name: 'Trakeena', box: 'Z' },
	{ id: 3021, name: 'Ransik', box: 'Z' },
];

export const monsters = [
	{ id: 2001, name: 'Madame Woe', box: 'A' },
	{ id: 2002, name: 'Pudgy Pig', box: 'A' },
	{ id: 2003, name: 'Bones', box: 'A' },
	{ id: 2004, name: 'Knasty Knight', box: 'A' },
	{ id: 2005, name: 'Commander Crayfish', box: 'D' },
	{ id: 2006, name: 'Polluticorn', box: 'D' },
	{ id: 2007, name: 'Ranger Slayer', box: 'C' },
	{ id: 2008, name: 'Black Dragon', box: 'C' },
	{ id: 2009, name: 'Pumpkin Rapper', box: 'B' },
	{ id: 2010, name: 'Eye Guy', box: 'B' },
	{ id: 2011, name: 'Rhinoblaster', box: 'B' },
	{ id: 2012, name: 'Robogoat', box: 'B' },
	{ id: 2013, name: 'Evil Green Ranger', box: 'B' },
	{ id: 2014, name: 'Finster', box: 'B' },
	{ id: 2015, name: 'Primator', box: 'B' },
	{ id: 2016, name: 'Evil Robot Tommy', box: 'H' },
	{ id: 2017, name: 'Psycho Red', box: 'L', nemesis: true },
	{ id: 2018, name: 'Psycho Black', box: 'L', nemesis: true },
	{ id: 2019, name: 'Psycho Blue', box: 'L', nemesis: true },
	{ id: 2020, name: 'Psycho Pink', box: 'L', nemesis: true },
	{ id: 2021, name: 'Psycho Yellow', box: 'L', nemesis: true },
	{ id: 2022, name: 'Psycho Green', box: 'L', nemesis: true },
	{ id: 2023, name: 'Prince Gasket & Princess Archerina', box: 'M' },
	{ id: 2024, name: 'Prince Gasket', box: 'M' },
	{ id: 2025, name: 'Princess Archerina', box: 'M' },
	{ id: 2026, name: 'General Venjix', box: 'M' },
	{ id: 2027, name: 'Squatt', box: 'P' },
	{ id: 2028, name: 'Squatt & Baboo', box: 'P' },
	{ id: 2029, name: 'Baboo', box: 'P' },
	{ id: 2030, name: 'Pirantishead', box: 'Q' },
	{ id: 2031, name: 'King Sphinx', box: 'Q' },
	{ id: 2032, name: 'Terror Toad', box: 'Q' },
	{ id: 2033, name: 'Dayne', box: 'R', nemesis: true },
	{ id: 2034, name: 'Blaze', box: 'R' },
	{ id: 2035, name: 'Roxy', box: 'R' },
	{ id: 2036, name: 'Darkonda', box: 'R' },
	{ id: 2037, name: 'Zen-Aku', box: 'S', nemesis: true },
	{ id: 2038, name: 'Cursed Tyzonn', box: 'S' },
	{ id: 2039, name: 'Koragg', box: 'S' },
	{ id: 2040, name: 'Snide', box: 'S' },
	{ id: 2041, name: 'Evil Dino Thunder White', box: 'T' },
	{ id: 2042, name: 'Zeltrax', box: 'Y', nemesis: true },
	{ id: 2043, name: 'Ecliptor', box: 'Y' },
	{ id: 2044, name: 'Elsa', box: 'Y' },
	{ id: 2045, name: 'Deker', box: 'Z', nemesis: true },
	{ id: 2046, name: 'Vrak', box: 'Z', nemesis: true },
	{ id: 2047, name: 'Frax', box: 'Z' },
	{ id: 2048, name: 'Heximas', box: 'AB' },
	{ id: 2049, name: 'Void Knight', box: 'AH' },
];

export const allBoxIds = boxes.map((box) => box.id);
// ... existing code ...
