export const presetPacks = [
	{
		id: 1,
		name: 'Morphin Master',
		boxes: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K'],
	},
	{ id: 2, name: 'All In-Wave 1', boxes: ['A', 'B', 'C', 'D', 'I'] },
	{ id: 3, name: 'All In-Wave 2', boxes: ['F', 'H', 'J', 'K'] },
];

export const boxes = [
	{ name: 'Heroes of the Grid Base Game', id: 'A' },
	{ name: 'Kickstarter Exclusives Box #1', id: 'B' },
	{ name: 'Shattered Grid', id: 'C' },
	{ name: 'Villian Pack #1', id: 'D' },
	{ name: 'Bulk and Skull Rangers', id: 'E' },
	{ name: 'Zeo Rangers', id: 'F' },
	{ name: 'Allies Pack #1', id: 'G' },
	{ name: 'Legendar Ranger: Tommy Oliver', id: 'H' },
	{ name: 'Cyclopsis', id: 'I' },
	{ name: 'Mega Goldar', id: 'J' },
	{
		name: 'Kickstarter Exclusives #2: Zeo Red Battlezord and Gold Zeo Ranger',
		id: 'K',
	},
];

export const soldiers = [
	{ id: 1, name: 'Putty Patrollers', box: 'A', image: '' },
	{ id: 2, name: 'Super Putty Patrollers', box: 'A', image: '' },
	{ id: 3, name: 'Tenga Warriors', box: 'B', image: '' },
	{ id: 4, name: 'Z-Putties', box: 'B', image: '' },
	{ id: 5, name: 'Mastadon Troopers', box: 'C', image: '' },
];

export const rangers = [
	{ id: 6, name: 'Kimberly Ann Hart', power: 'Mighty Morphin Pink', box: 'A' },
	{ id: 7, name: 'Jason Lee Scott', power: 'Mighty Morphin Red', box: 'A' },
	{ id: 8, name: 'Trini Kwan', power: 'Mighty Morphin Yellow', box: 'A' },
	{ id: 9, name: 'Zack Taylor', power: 'Mighty Morphin Black', box: 'A' },
	{ id: 10, name: 'Billy Cranston', power: 'Mighty Morphin Blue', box: 'A' },
	{
		id: 11,
		name: 'Eugene "Skull" Skullovitch',
		power: 'Mighty Morphin Orange',
		box: 'E',
	},
	{
		id: 12,
		name: 'Farkas "Bulk" Bulkmeier',
		power: 'Mighty Morphin Purple',
		box: 'E',
	},
	{ id: 13, name: 'Lauren Shiba', power: 'Super Samurai Red', box: 'C' },
	{ id: 14, name: 'Marvin Shih', power: 'HyperForce Red', box: 'C' },
	{ id: 15, name: 'Eddie Banks', power: 'HyperForce Blue', box: 'C' },
	{ id: 16, name: 'Chloe Ashford', power: 'HyperForce Pink', box: 'C' },
	{ id: 17, name: 'Jack Thomas', power: 'HyperForce Yellow', box: 'C' },
	{ id: 18, name: 'Vesper Vasquez', power: 'HyperForce Black', box: 'C' },
	{ id: 19, name: 'Jen Scotts', power: 'Time Force Pink', box: 'C' },
	{ id: 20, name: 'Kat Hillard', power: 'Mighty Morphin Pink', box: 'B' },
	{ id: 21, name: 'Aisha Campbell', power: 'Mighty Morphin Yellow', box: 'B' },
	{ id: 22, name: 'Rocky DeSantos', power: 'Mighty Morphin Red', box: 'B' },
	{ id: 23, name: 'Adam Park', power: 'Mighty Morphin Black', box: 'B' },
	{
		id: 24,
		name: 'Jason Lee Scott',
		power: 'Mighty Morphin Red',
		subset: 'Dragon Shield',
		box: 'B',
	},
	{ id: 25, name: 'Kimberly Ann Hart', power: 'Rebel Ranger Slayer', box: 'B' },
	{
		id: 26,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Loner',
		box: 'B',
	},
	{
		id: 27,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Guardian Light',
		box: 'B',
	},
	{
		id: 32,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Loner',
		box: 'H',
	},
	{
		id: 33,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Guardian Light',
		box: 'H',
	},
	{
		id: 28,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin White',
		subset: 'Rallying Light',
		box: 'H',
	},
	{
		id: 29,
		name: 'Tommy Oliver',
		power: 'Mighty Morphin Green',
		subset: 'Gift of the Dragon',
		box: 'H',
	},
	{ id: 30, name: 'Tommy Oliver', power: 'Dino Thunder Black', box: 'H' },
	{ id: 1, name: 'Tommy Oliver', power: 'Turbo Red', box: 'H' },
	{ id: 2, name: 'Tommy Oliver', power: 'Zeo Ranger V Red', box: 'F' },
	{ id: 3, name: 'Adam Park', power: 'Zeo Ranger IV Green', box: 'F' },
	{ id: 4, name: 'Rocky DeSantos', power: 'Zeo Ranger III Blue', box: 'F' },
	{ id: 5, name: 'Tanya Sloan', power: 'Zeo Ranger II Yellow', box: 'F' },
	{ id: 31, name: 'Kat Hillard', power: 'Zeo Ranger I Pink', box: 'F' },
]; // add 2 gold rangers and allies pack

export const megazords = [
	{ id: 1, name: 'Dino Megazord', box: 'A' },
	{ id: 2, name: 'Chronos HyperForce Megazord', box: 'C' },
	{ id: 3, name: 'Zeo Megazord', box: 'F' },
	{ id: 4, name: 'Dragonzord Battle Mode', box: 'H' },
];

export const zords = [
	{ id: 1, name: 'Pterodactyl', box: 'A' },
	{ id: 2, name: 'Triceratops', box: 'A' },
	{ id: 3, name: 'Mastodon', box: 'A' },
	{ id: 4, name: 'Saber-Toothed Tiger', box: 'A' },
	{ id: 5, name: 'Tyrannosaurus', box: 'A' },
	{ id: 6, name: 'Dragonzord', box: 'B' },
	{ id: 7, name: 'White Tigerzord', box: 'B' },
	{ id: 8, name: 'Ram Hyper Zord', box: 'C' },
	{ id: 9, name: 'Phoenix Hyper Zord', box: 'C' },
	{ id: 10, name: 'Serpent Hyper Zord', box: 'C' },
	{ id: 11, name: 'Cerberus Hyper Zord', box: 'C' },
	{ id: 12, name: 'Lion Hyper Zord', box: 'C' },
	{ id: 13, name: 'Gravezord', box: 'C' },
	{ id: 14, name: 'Bullzord', box: 'C' },
	{ id: 15, name: 'Time Flyer 5', box: 'C' },
	{ id: 16, name: 'Featherdactyl', box: 'E' },
	{ id: 17, name: 'Baconodon', box: 'E' },
	{ id: 18, name: 'Brachiozord', box: 'H' },
	{ id: 19, name: 'Lightning Cruiser', box: 'H' },
	{ id: 20, name: 'White Tigerzord', box: 'H' },
	{ id: 21, name: 'Dragonzord', box: 'H' },
	{ id: 22, name: 'Zeo Zord V', box: 'F' },
	{ id: 23, name: 'Zeo Zord IV', box: 'F' },
	{ id: 24, name: 'Zeo Zord III', box: 'F' },
	{ id: 25, name: 'Zeo Zord II', box: 'F' },
	{ id: 26, name: 'Zeo Zord I', box: 'F' },
	{ id: 26, name: 'Red Zeo Battlezord', box: 'K' },
];

export const masters = [
	{ id: 1, name: 'Rita Repulsa', box: 'A' },
	{ id: 2, name: 'Master Vile', box: 'D' },
	{ id: 3, name: 'Rito Revolto', box: 'D' },
	{ id: 4, name: 'Lord Drakkon', box: 'C' },
	{ id: 5, name: 'Cyclopsis', box: 'I' },
	{ id: 6, name: 'Mega Goldar', box: 'J' },
	{ id: 7, name: 'Scorpina', box: 'B' },
	{ id: 8, name: 'Goldar', box: 'B' },
	{ id: 9, name: 'Lord Zedd', box: 'B' },
	{ id: 10, name: 'Wizard of Deception', box: 'B' },
];

export const monsters = [
	{ id: 1, name: 'Madame Woe', box: 'A' },
	{ id: 2, name: 'Pudgy Pig', box: 'A' },
	{ id: 3, name: 'Bones', box: 'A' },
	{ id: 4, name: 'Knasty Knight', box: 'A' },
	{ id: 5, name: 'Commander Crayfish', box: 'D' },
	{ id: 6, name: 'Polluticorn', box: 'D' },
	{ id: 7, name: 'Ranger Slayer', box: 'C' },
	{ id: 8, name: 'Black Dragon', box: 'C' },
	{ id: 9, name: 'Pumpkin Rapper', box: 'B' },
	{ id: 10, name: 'Eye Guy', box: 'B' },
	{ id: 11, name: 'Rhinoblaster', box: 'B' },
	{ id: 12, name: 'Robogoat', box: 'B' },
	{ id: 13, name: 'Evil Green Ranger', box: 'B' },
	{ id: 14, name: 'Finster', box: 'B' },
	{ id: 15, name: 'Primator', box: 'B' },
];
